### ISSUE TITLE
Unable to find suggested architecture and technology stack

### ISSUE THREAD

**Issue by terribleherbst** [hafven/community-api#8]
Just found out, there has been some decission about a suggested architecture and technoloy stack. I was unable to attend the last meeting can you help me, where I can find this information?

**Comment by muenalan** [comment]
+1: Just to keep track what is discussed/decided. Added New Projects Board [Meetings](https://github.com/hafven/community-api/projects/2). Column Upcoming: The next meeting is filled with suggestions -> Moved to history once it is filled with notes/done. Slack might be a better option ?!
